add starttls (postgres flavour):
Daimler/traefik pull request #2
Opened 2020-11-27 13:38 UTC by maigl

### What does this PR do?

### Motivation

### More

- [ ] Added/updated tests
- [ ] Added/updated documentation

### Additional Notes

2020-11-27 15:08 UTC, maigl commented
@matoubidou @MoritzKeppler @sbueringer could you plz review ?

2020-12-03 14:59 UTC, MoritzKeppler reviewed
just two minor things - more (if found) will follow soon.

2020-12-03 14:59 UTC, MoritzKeppler commented on pkg/tcp/starttls.go
> +		return fmt.Errorf("unexpected postgres starttls response got %v want 'S' ", b)
```suggestion
		return fmt.Errorf("unexpected postgres starttls response got %v want %s ", b, PostgresStartTLSReply[0])
```

2020-12-03 14:59 UTC, MoritzKeppler commented on pkg/tcp/starttls.go
> +		// we only support secure connections otherwise we wouldn't get any SNI header
SNI is just mandatory in our case, right?

2020-12-04 07:15 UTC, chrischdi commented
in your description:
`This adds postgres starttls postgres support which allows to reverse proxy postgres connection through traefik (via SNI).`
> adds postgres starttls postgres support?!

2020-12-04 07:37 UTC, maigl commented on pkg/tcp/starttls.go
> +		// we only support secure connections otherwise we wouldn't get any SNI header
I believe it's mandatory .. but may be I don't get it ?!

2020-12-04 21:50 UTC, TSSven requested changes
My humble contribution... merely a spell check

2020-12-04 21:50 UTC, TSSven commented on pkg/server/server_entrypoint_tcp_test.go
> +		t.Fatalf("Expected Start TLS reply but got %v: ", buf[0])
```suggestion
		t.Fatalf("Expected StartTLS reply but got %v: ", buf[0])
```

2020-12-04 21:50 UTC, TSSven commented on pkg/tcp/router.go
> +	// starttls handshake (postgres). It works in both cases,
```suggestion
	// StartTLS handshake (postgres). It works in both cases,
```

2020-12-04 21:50 UTC, TSSven commented on pkg/tcp/router.go
> +	// starttls handshake (postgres). It works in both cases,
I'm not quite sure what the word group "StartTLS handshake (postgres)" is supposed to say.
Is the handshake postgres-specific, i.e. "StartTLS handshake for postgres"?[1]
Or could this be used in use cases too? If so, the comment should convey this.

[1]
I also checked [rfc2487](https://tools.ietf.org/html/rfc2487) and from what I understood they do call the first activity after executing the STARTTLS command "TLS negotiation". Maybe using this phrase will in some cases make it easier to distinguish and understand for the reader. --> In the example above: "start TLS negotiation for postgres"?

2020-12-04 21:50 UTC, TSSven commented on pkg/tcp/starttls.go
> +// are unmodified.
```suggestion
// remain unmodified.
```

2020-12-04 21:50 UTC, TSSven commented on pkg/tcp/starttls_test.go
> +// The proxy must match the the backend. I.e. if backend expect StartTLS we have
```suggestion
// The proxy must match the the backend. I.e. if the backend expects StartTLS we have
```

2020-12-04 21:50 UTC, TSSven commented on pkg/tcp/starttls_test.go
> +			name:                 "proxy  and backend want starttls",
```suggestion
			name:                 "proxy and backend want starttls",
```

2020-12-14 10:14 UTC, matoubidou commented on pkg/tcp/router.go
> +func (r *Router) ConnectionFilter(name string, filterFunc func(WriteCloser) (WriteCloser, error)) {
More precisely we are not filtering connections but rather enabling to peek into a connection or to read some bytes before the connection is routed. I would prefer a word reflecting this behaviour. What about `PreRoutingHook`?

2021-01-04 07:03 UTC, sbueringer commented
@maigl all findings adressed? Should I also take a look?

2021-01-12 15:40 UTC, maigl reviewed
> @maigl all findings adressed? Should I also take a look?

of course .. but I'm not done fixing the findings .. let me finish this first ..

2021-02-04 16:48 UTC, maigl reviewed
> @maigl all findings adressed? Should I also take a look?

@sbueringer yes I think now would be a good time if you could share you thoughts on this! :)

2021-02-04 16:48 UTC, maigl commented on pkg/tcp/starttls_test.go
> +					time.Sleep(1 * time.Millisecond)
don't know how .. maybe we could team up on this .

2021-09-30 13:54 UTC, maigl commented
outdated .. new try

2021-09-30 13:54 UTC, closed without merging